AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: 'Create application loadbalancer'

Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets: [ 'Fn::ImportValue': !Sub 'example-vpc-public-az-a-subnet', 'Fn::ImportValue': !Sub 'example-vpc-public-az-b-subnet' ]
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup

  HttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        # !Subは使えなかった
        - TargetGroupArn: !ImportValue target-group-arn
          Type: forward
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP

  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId: !ImportValue example-vpc-vpc-id
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:
  ApplicationLoadBalancerDNSName:
    Description: Application Load Balancer DNS Name
    Value: !GetAtt LoadBalancer.DNSName
  ApplicationLoadBalancerSecurityGroup:
    Description: Application Load Balancer Security Grout
    Value: !Ref LoadBalancerSecurityGroup
    Export:
      Name: load-balancer-security-group
