AWSTemplateFormatVersion: '2010-09-09'
Description: "DynamoDB Global Table Replica Test"

# --------------------------------------------- #
# Metadata
# --------------------------------------------- #
# Organizes How the Parameters appear in the CloudFormation Interface
# cloudformationをGUIで入力するときに求められるパラメーター画面
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: 'Dynamodb Parameter'
        Parameters:
          - NotificationsTableName
          - UsersTableName

# --------------------------------------------- #
# Parameters
# --------------------------------------------- #
Parameters:
  ProjectName:
    Type: String

  NotificationsTableName:
    Description: 'Notifications table name'
    Type: String
    Default: 'Notifications'
    AllowedPattern: '[a-zA-Z0-9_.-]+'
    MaxLength: 255
    MinLength: 3

  UsersTableName:
    Description: 'Users table name'
    Type: String
    Default: 'Users'
    AllowedPattern: '[a-zA-Z0-9_.-]+'
    MaxLength: 255
    MinLength: 3

# --------------------------------------------- #
# Resources
# --------------------------------------------- #
# スタックを削除してもdynamodbのテーブルは削除されないので注意
Resources:
  # ----------------------------------------------------- #
  # Dynamodb Table
  # ----------------------------------------------------- #
  NotificationsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: !Ref NotificationsTableName
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  UsersTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: !Ref UsersTableName
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

# --------------------------------------------- #
# Outputs
# --------------------------------------------- #
Outputs:
  NotificationsTableArn:
    Value: !GetAtt NotificationsTable.StreamArn
    Export:
      Name: !Sub ${ProjectName}-notifications-table-arn
  UsersTableArn:
    Value: !GetAtt UsersTable.StreamArn
    Export:
      Name: !Sub ${ProjectName}-users-table-arn
